on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0   # Node + git уже есть

    steps:
      - name: Wait for 10 seconds
        run: sleep 10

      
      - name: Clone repository
        run: |
          git clone http://x-access-token:fa4f3ddfe5dae5d82e362376cc1a6762475d99af@gitea:3000/admin/CodeMetricsBackend.git .
          git checkout ${{ github.sha }}
      
      - name: Install SonarScanner for .NET
        run: |
            dotnet tool install --global dotnet-sonarscanner

      
      - name: Begin SonarScanner
        run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet sonarscanner begin \
            /k:"renam" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="http://sonarqube:9000"

      - name: Build project
        run: |
            echo "Workspace: $GITHUB_WORKSPACE"
            ls -la $GITHUB_WORKSPACE
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet build

      - name: End SonarScanner (upload results)
        run: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"