// <auto-generated />
using System;
using CodeMetrics.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeMetrics.Migrations
{
    [DbContext(typeof(CodeMetricsDbContext))]
    [Migration("20251025083239_FixMigrations")]
    partial class FixMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeMetrics.Entity.Branch", b =>
                {
                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("lastCommitHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("repoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BranchName");

                    b.HasIndex("lastCommitHash")
                        .IsUnique();

                    b.HasIndex("repoName");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CodeMetrics.Entity.Commit", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("authorEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("authorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("committerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("committerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("repoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Hash");

                    b.HasIndex("authorEmail");

                    b.HasIndex("committerEmail");

                    b.HasIndex("repoName");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("CodeMetrics.Entity.CommitStats", b =>
                {
                    b.Property<string>("CommitHash")
                        .HasColumnType("text");

                    b.Property<int>("AddedLines")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedFiles")
                        .HasColumnType("integer");

                    b.Property<int>("DeletedLines")
                        .HasColumnType("integer");

                    b.HasKey("CommitHash");

                    b.HasIndex("CommitHash")
                        .IsUnique();

                    b.ToTable("CommitStats");
                });

            modelBuilder.Entity("CodeMetrics.Entity.Project", b =>
                {
                    b.Property<string>("ProjectKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectKey");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("CodeMetrics.Entity.Repository", b =>
                {
                    b.Property<string>("RepoName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFork")
                        .HasColumnType("boolean");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RepoName");

                    b.HasIndex("ProjectKey");

                    b.HasIndex("RepoName");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("CodeMetrics.Entity.User", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserEmail");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeMetrics.Entity.Branch", b =>
                {
                    b.HasOne("CodeMetrics.Entity.Commit", null)
                        .WithOne()
                        .HasForeignKey("CodeMetrics.Entity.Branch", "lastCommitHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeMetrics.Entity.Repository", null)
                        .WithMany()
                        .HasForeignKey("repoName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeMetrics.Entity.Commit", b =>
                {
                    b.HasOne("CodeMetrics.Entity.CommitStats", null)
                        .WithOne()
                        .HasForeignKey("CodeMetrics.Entity.Commit", "Hash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeMetrics.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("authorEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeMetrics.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("committerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeMetrics.Entity.Repository", null)
                        .WithMany()
                        .HasForeignKey("repoName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeMetrics.Entity.Repository", b =>
                {
                    b.HasOne("CodeMetrics.Entity.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
